matrix:
  include:
    - language: python
      python: 3.6
      script:
      - pip install pipenv
      - pipenv install

    - language: node_js
      node_js: 
      - "9"
      script:
      - yarn install
